apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  labels:
    app: go-api
    component: backend
    environment: aws
spec:
  replicas: 2  # AWS - mais réplicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
        component: backend
        environment: aws
    spec:
      containers:
      - name: go
        image: go-api:latest  # Será substituído dinamicamente
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: database-config
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-config
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-config
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-config
              key: dbname
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: database-config
              key: port
        - name: PORT
          value: "8000"
        
        resources:
          requests:
            memory: "256Mi"  # AWS - mais recursos
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        
        # Health checks para AWS
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 90  # AWS - mais tempo
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      
      restartPolicy: Always
