apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-api-dev

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

labels:
- pairs:
    app: go-api
    environment: local
  includeSelectors: true

# Configuração LOCAL - host.docker.internal + credenciais root/root
secretGenerator:
- name: database-config
  literals:
  - host=host.docker.internal
  - port=5432
  - username=root
  - password=root
  - dbname=root

images:
- name: bielvieira/go_ci
  newTag: "40"
