apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  labels:
    app: go-api
    environment: local
spec:
  type: NodePort  # Local - NodePort para acesso via localhost:30080
  selector:
    app: go-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
      name: http
