apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  labels:
    app: go-api
spec:
  type: NodePort  # Local - NodePort
  selector:
    app: go-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
      name: http
