apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  labels:
    app: go-api
spec:
  type: LoadBalancer
  selector:
    app: go-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: go-api-internal
  labels:
    app: go-api
spec:
  type: ClusterIP
  selector:
    app: go-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
