apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: go
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
